[project]
name = "ascii-art"
version = "0.0.2"
description = "To write ascii art"
dependencies = ["pyperclip==1.8.2"]


[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

